# Generated by Django 2.0.7 on 2018-07-25 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180725_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
