# Generated by Django 2.0.7 on 2018-07-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Первый'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_four',
            field=models.TextField(default='content_four', max_length=1000, verbose_name='Четвертый'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_three',
            field=models.TextField(default='content_three', max_length=1000, verbose_name='Третий'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_two',
            field=models.TextField(default='content_two', max_length=1000, verbose_name='Второй'),
        ),
    ]
