# Generated by Django 2.0.7 on 2018-08-09 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_auto_20180728_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='disliked',
            field=models.ManyToManyField(blank=True, related_name='disliked_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
