# Generated by Django 2.0.7 on 2018-07-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_account',
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_account',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Профиль Facebook'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название предприятия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_account',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Профиль LinkedIn'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_url',
            field=models.URLField(blank=True, max_length=555, null=True, verbose_name='Сайт компании'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Картинка профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='short_bio',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Должность'),
        ),
    ]
