# Generated by Django 2.0.7 on 2018-09-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180908_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(choices=[('A', 'A.'), ('B', 'B.'), ('C', 'C.')], default='A', max_length=6),
        ),
    ]
