# Generated by Django 2.0.7 on 2018-09-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('akmola', 'Акмолинская область'), ('aktobe', 'Актюбинская область'), ('almaty', 'Алматинская область'), ('atyrau', 'Атырауская область'), ('eastern', 'Восточно-Казахстанская область'), ('dzhambul', 'Жамбылская область'), ('western', 'Западно-Казахстанская область'), ('karaganda', 'Карагандинская область'), ('kostanai', 'Костанайская область'), ('kyzylorda', 'Кызылординская область'), ('mangystau', 'Мангистауская область'), ('pavlodar', 'Павлодарская область'), ('north', 'Северо-Казахстанская область'), ('turkestan', 'Туркестанская область')], default='akmola', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, choices=[('A', 'A.'), ('B', 'B.'), ('C', 'C.')], default='A', max_length=6, verbose_name='Вид деятельности'),
        ),
    ]
