# Generated by Django 2.0.7 on 2018-09-08 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180908_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер должен быть в формате: '+7xxxxxxxxxx' или '8xxxxxxxxxx'.", regex='^\\+?1?\\d{11}$')], verbose_name='Номер телефона'),
        ),
    ]
