# Generated by Django 2.0.7 on 2018-09-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180912_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=555, null=True, verbose_name='О компании'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Сайт компании'),
        ),
    ]
