# Generated by Django 2.0.7 on 2018-09-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180829_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, upload_to='article_files/%Y/%m/%d/', verbose_name='Загрузить файл'),
        ),
    ]
