# Generated by Django 2.0.7 on 2018-08-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20180825_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title_two',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
