# Generated by Django 2.0.7 on 2018-08-25 17:03

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20180825_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content_two',
            field=markdownx.models.MarkdownxField(default='null'),
        ),
    ]
