# Generated by Django 2.0.7 on 2018-08-26 12:38

from django.db import migrations, models
import markdownx.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_auto_20180825_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content_two',
            field=markdownx.models.MarkdownxField(default='null', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_two',
            field=models.CharField(default='null', max_length=200, verbose_name='Заговолок'),
        ),
    ]
