# Generated by Django 2.0.7 on 2018-08-26 14:10

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_auto_20180826_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='content_two',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_two',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title_two',
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Заголовок'),
        ),
    ]
