# Generated by Django 2.0.7 on 2018-08-27 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import taggit.managers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0008_answer2_question2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer3',
            fields=[
                ('content', markdownx.models.MarkdownxField()),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_votes', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_answer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Answer3',
                'verbose_name_plural': 'Answers3',
                'ordering': ['-is_answer', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Question3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Заголовок')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('D', 'Draft')], default='D', max_length=1)),
                ('content', markdownx.models.MarkdownxField(verbose_name='Контент')),
                ('has_answer', models.BooleanField(default=False)),
                ('total_votes', models.IntegerField(default=0)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question3',
                'verbose_name_plural': 'Questions3',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='answer2',
            options={'ordering': ['-is_answer', '-timestamp'], 'verbose_name': 'Answer2', 'verbose_name_plural': 'Answers2'},
        ),
        migrations.AlterModelOptions(
            name='question2',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Question2', 'verbose_name_plural': 'Questions2'},
        ),
        migrations.AlterField(
            model_name='answer2',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Question2'),
        ),
        migrations.AddField(
            model_name='answer3',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Question2'),
        ),
        migrations.AddField(
            model_name='answer3',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
