# Generated by Django 2.0.7 on 2018-08-29 08:33

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0011_auto_20180828_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(default='', upload_to='forum_files/%Y/%m/%d/', verbose_name='Загрузить файл'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Список тэгов через запятую.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='question2',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Список тэгов через запятую.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='question3',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Список тэгов через запятую.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='question4',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Список тэгов через запятую.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='question5',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Список тэгов через запятую.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='question6',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Список тэгов через запятую.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='question7',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Список тэгов через запятую.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='question8',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Список тэгов через запятую.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги'),
        ),
    ]
