# Generated by Django 2.0.7 on 2018-08-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0012_auto_20180829_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='question2',
            name='file',
            field=models.FileField(default='', upload_to='forum_files/%Y/%m/%d/', verbose_name='Загрузить файл'),
        ),
        migrations.AddField(
            model_name='question3',
            name='file',
            field=models.FileField(default='', upload_to='forum_files/%Y/%m/%d/', verbose_name='Загрузить файл'),
        ),
        migrations.AddField(
            model_name='question4',
            name='file',
            field=models.FileField(default='', upload_to='forum_files/%Y/%m/%d/', verbose_name='Загрузить файл'),
        ),
        migrations.AddField(
            model_name='question5',
            name='file',
            field=models.FileField(default='', upload_to='forum_files/%Y/%m/%d/', verbose_name='Загрузить файл'),
        ),
        migrations.AddField(
            model_name='question6',
            name='file',
            field=models.FileField(default='', upload_to='forum_files/%Y/%m/%d/', verbose_name='Загрузить файл'),
        ),
        migrations.AddField(
            model_name='question7',
            name='file',
            field=models.FileField(default='', upload_to='forum_files/%Y/%m/%d/', verbose_name='Загрузить файл'),
        ),
        migrations.AddField(
            model_name='question8',
            name='file',
            field=models.FileField(default='', upload_to='forum_files/%Y/%m/%d/', verbose_name='Загрузить файл'),
        ),
    ]
