# Generated by Django 2.0.7 on 2018-09-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0015_auto_20180829_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='file',
            field=models.FileField(default='', upload_to='forum_files/%Y/%m/%d/', verbose_name='Загрузить файл'),
        ),
    ]
